Repository EvoEsports/EvoSC-sharp, pull requests merged in 2024-10, with the labels that each got.

#312 Don't start manual tracking if automatic tracking is enabled.
  src/Modules/MatchTrackerModule/Controllers/MatchTrackerEventController.cs
  tests/Modules/MatchTrackerModule.Tests/Controllers/MatchTrackerEventControllerTests.cs
Labels: pr: backwards compatible, pr: bugfix

#307 Add time difference to local record announcement (#278)
  src/Modules/LocalRecordsModule/Services/LocalRecordsService.cs
  tests/Modules/LocalRecordsModule.Tests/Services/LocalRecordsServiceTests.cs
Labels: pr: backwards compatible, pr: new feature

#309 WRM: Handle Flurl http exceptions
  src/Modules/WorldRecordModule/Interfaces/IWorldRecordService.cs
  src/Modules/WorldRecordModule/Services/WorldRecordService.cs
Labels: pr: backwards compatible
